- name: Setup environment
  block:
  - name: 'Create {{ working_dir }}'
    ansible.builtin.file:
      path: '{{ working_dir }}'
      state: directory
  - name: 'Create {{ working_dir }}/k8s'
    ansible.builtin.file:
      path: '{{ working_dir }}/k8s'
      state: directory
- name: Setup keycloak
  block:
  - name: Template a file to k8s/deployment.yml
    ansible.builtin.template:
      src: k8s/deployment.yml.j2
      dest: '{{ working_dir }}/k8s/deployment.yml'
  - name: Apply Deployment manifest to the cluster
    community.kubernetes.k8s:
      src: '{{ working_dir }}/k8s/deployment.yml'
      state: present
  - name: Template a file to k8s/service.yml
    ansible.builtin.template:
      src: k8s/service.yml.j2
      dest: '{{ working_dir }}/k8s/service.yml'
  - name: Apply Service manifest to the cluster
    community.kubernetes.k8s:
      src: '{{ working_dir }}/k8s/service.yml'
      state: present
  - name: Template a file to k8s/ingress.yml
    ansible.builtin.template:
      src: k8s/ingress.yml.j2
      dest: '{{ working_dir }}/k8s/ingress.yml'
  - name: Apply Ingress manifest to the cluster
    community.kubernetes.k8s:
      src: '{{ working_dir }}/k8s/ingress.yml'
      state: present
