- name: 'clone {{ working_git }}'
  ansible.builtin.git:
    repo: '{{ working_git }}'
    dest: '{{ working_dir }}'
- name: start keycloak
  docker_container:
    name: proyek3-keycloak
    image: quay.io/keycloak/keycloak:12.0.4
    state: started
    recreate: yes
    restart: yes
    restart_policy: unless-stopped
    network_mode: '{{ docker_bridge_network }}'
    networks:
      - name: '{{ docker_bridge_network }}'
        ipv4_address: '{{ docker_ipv4_address_keycloak }}'
    mounts:
      - source: '{{ working_dir }}/opt/jboss/keycloak/themes/proyek3-theme'
        target: /opt/jboss/keycloak/themes/proyek3-theme
        type: bind
    env:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: postgres
      DB_ADDR: '{{ docker_ipv4_address_postgres }}'
      DB_USER: proyek3
      DB_PASSWORD: proyek3
      DB_DATABASE: proyek3
      DB_SCHEMA: keycloak
