all:
  hosts:
    mail.example.com:
  children:
    deployment:
      hosts:
        202.157.177.52:
          ansible_port: 8288
          ansible_user: proyek3
          ansible_password: proyek3
          ansible_become_password: proyek3
      vars:
        docker_bridge_network: proyek3-network
        docker_subnet: 172.18.0.0/16
        docker_ipv4_address_nginx: 172.18.0.2
        docker_ipv4_address_postgres: 172.18.0.3
        docker_ipv4_address_keycloak: 172.18.0.4
        maintainer_email: raefaldhi.amartya.tif418@polban.ac.id
