- name: Add registry to mirror list
  ansible.builtin.template:
    src: containerd-template.toml.j2
    dest: '/var/snap/microk8s/current/args/containerd-template.toml'

- name: Stop microk8s daemon
  become: yes
  shell:
    cmd: microk8s stop

- name: Start microk8s daemon
  become: yes
  shell:
    cmd: microk8s start

- name: Wait for microk8s to start
  shell:
    cmd: microk8s status --wait-ready

- name: Setup data storage
  block:
  - name: 'Create {{ storage_dir }}'
    ansible.builtin.file:
      path: '{{ storage_dir }}'
      state: directory

  - name: 'Create {{ storage_data_0_dir }}'
    ansible.builtin.file:
      path: '{{ storage_data_0_dir }}'
      state: directory

  - name: Apply PersistentVolumes to the cluster
    kubernetes.core.k8s:
      state: present
      template: k8s/persistent-volume.yml.j2

- name: Apply StatefulSet manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/stateful-set.yml.j2

- name: Apply Service manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/service.yml.j2

- name: Apply Ingress manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/ingress.yml.j2 