storage_dir: '{{ system_storage_dir }}/mongodb'

storage_data_0_dir: '{{ storage_dir }}/data-0'

mongodb_username: proyek3
mongodb_password: proyek3

MONGO_INITDB_ROOT_USERNAME: proyek3
MONGO_INITDB_ROOT_PASSWORD: proyek3