- name: 'Prepare {{ frontend_manifest }}'
  block:
  - name: 'Clone {{ frontend_git }}'
    ansible.builtin.git:
      repo: '{{ frontend_git }}'
      dest: '{{ frontend_dir }}'
      version: '{{ frontend_git_version }}'
    register: frontend_gitresult

  - name: 'Build {{ frontend_manifest }} image'
    containers.podman.podman_image:
      name: '{{ frontend_manifest }}'
      tag: '{{ frontend_gitresult.after }}'
      path: '{{ frontend_dir }}'
      push: yes
      push_args:
        dest: '{{ container_registry }}'
      validate_certs: no

- name: 'Prepare {{ keycloak_proxy_manifest }}'
  block:
  - name: 'Clone {{ keycloak_proxy_git }}'
    ansible.builtin.git:
      repo: '{{ keycloak_proxy_git }}'
      dest: '{{ keycloak_proxy_dir }}'
      version:  '{{ keycloak_proxy_git_version }}'
    register: keycloak_proxy_gitresult

  - name: 'Build {{ keycloak_proxy_manifest }} image'
    containers.podman.podman_image:
      name: '{{ keycloak_proxy_manifest }}'
      tag: '{{ keycloak_proxy_gitresult.after }}'
      path: '{{ keycloak_proxy_dir }}'
      push: yes
      push_args:
        dest: '{{ container_registry }}'
      validate_certs: no

- name: Apply Deployment manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/deployment.yml.j2

- name: Apply Service manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/service.yml.j2

- name: Apply Ingress manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/ingress.yml.j2