- name: 'Clone {{ workspace_git }}'
  ansible.builtin.git:
    repo: '{{ workspace_git }}'
    dest: '{{ workspace_dir }}'
    version: '{{ workspace_git_version }}'
  register: workspace_gitresult

- name: 'Prepare {{ backend_manifest }}'
  block:
  - name: 'Clone {{ backend_git }}'
    ansible.builtin.git:
      repo: '{{ backend_git }}'
      dest: '{{ backend_dir }}'
      version: '{{ backend_git_version }}'
    register: backend_gitresult

  - name: 'Clone {{ postgres_database_git }}'
    ansible.builtin.git:
      repo: '{{ postgres_database_git }}'
      dest: '{{ postgres_database_dir }}'
      version: '{{ postgres_database_git_version }}'

  - name: 'Build {{ backend_manifest }} image'
    containers.podman.podman_image:
      name: '{{ backend_manifest }}'
      tag: '{{ backend_gitresult.after }}'
      path: '{{ workspace_dir }}'
      push: yes
      push_args:
        dest: '{{ container_registry }}'
      validate_certs: no
      build:
        extra_args: '--file {{ backend_dir }}/Dockerfile'

- name: Apply Deployment manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/deployment.yml.j2

- name: Apply Service manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/service.yml.j2

- name: Apply Ingress manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/ingress.yml.j2