- name: 'Prepare {{ service_monitoring_name }}'
  block:
  - name: 'Clone {{ service_workspace_git }}'
    ansible.builtin.git:
      repo: '{{ service_workspace_git }}'
      dest: '{{ service_workspace_dir }}'
      version: main
    register: service_workspace_gitresult

  - name: 'Clone {{ service_monitoring_working_git }}'
    ansible.builtin.git:
      repo: '{{ service_monitoring_working_git }}'
      dest: '{{ service_monitoring_working_dir }}'
      version: main
    register: service_monitoring_gitresult

  - name: 'Clone {{ service_database_working_git }}'
    ansible.builtin.git:
      repo: '{{ service_database_working_git }}'
      dest: '{{ service_database_working_dir }}'
      version: main
    register: service_database_gitresult

  - name: 'Build {{ service_monitoring_name }} image'
    containers.podman.podman_image:
      name: '{{ service_monitoring_name }}'
      tag: '{{ service_monitoring_gitresult.after }}'
      path: '{{ service_monitoring_working_dir }}'
      push: yes
      push_args:
        dest: '{{ service_container_registry }}'
      validate_certs: no

- name: 'Prepare {{ service_frontend_name }}'
  block:
  - name: 'Clone {{ service_frontend_working_git }}'
    ansible.builtin.git:
      repo: '{{ service_frontend_working_git }}'
      dest: '{{ service_frontend_working_dir }}'
      version: main
    register: service_frontend_gitresult

  - name: 'Build {{ service_frontend_name }} image'
    containers.podman.podman_image:
      name: '{{ service_frontend_name }}'
      tag: '{{ service_frontend_gitresult.after }}'
      path: '{{ service_frontend_working_dir }}'
      push: yes
      push_args:
        dest: '{{ service_container_registry }}'
      validate_certs: no
  
- name: Apply Deployment manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/deployment.yml.j2

- name: Apply Service manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/service.yml.j2

- name: Apply Ingress manifest to the cluster
  kubernetes.core.k8s:
    state: present
    template: k8s/ingress.yml.j2