- name: Initialize system
  block:
  - name: Install snap
    become: yes
    apt:
      name: snapd
  - name: Install snap core
    become: yes
    snap:
      name: core
      state: present
  - name: 'Install apache2-utils'
    become: yes
    apt:
      name: apache2-utils
      state: present
  tags: ['never', 'init']
