- name: Update package cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade package
  become: yes
  apt:
    upgrade: full

- name: Install snap
  become: yes
  apt:
    name: snapd

- name: Install snap core
  become: yes
  snap:
    name: core
    state: present

- name: Install apache2-utils
  become: yes
  apt:
    name: apache2-utils
    state: present

- name: Install python3-pip
  become: yes
  apt:
    name: python3-pip
    state: present