- name: create system_dir
  file:
    path: '{{ system_dir }}'
    state: directory
  tags:
    - setup
- name: install docker sdk
  pip:
    name: docker
  tags: 
    - setup
- name: create docker bridge network
  docker_network:
    name: proyek3-network
    ipam_config:
      - subnet: 172.18.0.0/16
  tags:
    - setup
