- name: create system_dir
  file:
    path: '{{ system_dir }}'
    state: directory
- name: install docker sdk
  pip:
    name: docker
- name: create docker bridge network
  docker_network:
    name: '{{ docker_bridge_network }}'
    ipam_config:
      - subnet: '{{ docker_subnet }}'
