working_dir: '{{ system_tmp_dir }}/registry'
storage_dir: '{{ system_storage_dir }}/registry'

storage_auth_dir: '{{ system_storage_dir }}/registry/auth'
storage_certs_dir: '{{ system_storage_dir }}/registry/certs'
storage_data_0_dir: '{{ system_storage_dir }}/registry/data-0'

registry_hostname: registry.6766998f.nip.io
registry_username: proyek3
registry_password: '{{ vault_registry_password }}'
